# Generated by Django 3.1.1 on 2021-07-29 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfoUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('site_id', models.CharField(max_length=2)),
                ('long_name', models.CharField(max_length=32)),
                ('release_lag', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('site_reference', models.TextField()),
                ('data_doi', models.TextField()),
                ('data_reference', models.TextField()),
                ('data_revision', models.CharField(max_length=8)),
                ('extra_fields', models.JSONField(default=dict)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
