# Generated by Django 3.2.6 on 2021-08-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFileLocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.TextField()),
                ('starttime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='contact',
            field=models.CharField(help_text='Point of contact for the TCCON site. Must be formatted "Name &lt;email&gt;"', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='data_reference',
            field=models.TextField(help_text='Citation to use for the data from this TCCON site. Optional'),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='location',
            field=models.CharField(help_text='Where the TCCON site is located (e.g. institution, city, state/province, country)', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='release_lag',
            field=models.PositiveIntegerField(help_text='Number of days to withhold data'),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='site_reference',
            field=models.TextField(help_text='Citation to use for the TCCON site itself. Optional'),
        ),
    ]
