# Generated by Django 3.2.6 on 2021-08-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_auto_20210810_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfoupdate',
            name='extra_fields',
        ),
    ]
