# Generated by Django 3.2.6 on 2021-08-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_remove_siteinfoupdate_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofilelocks',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
