# Generated by Django 3.2.6 on 2021-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_infofilelocks_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='data_reference',
            field=models.TextField(default='', help_text='Citation to use for the data from this TCCON site. Optional'),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='site_reference',
            field=models.TextField(default='', help_text='Citation to use for the TCCON site itself. Optional'),
        ),
    ]
