# Generated by Django 3.2.6 on 2021-08-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0005_auto_20210811_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='contact',
            field=models.CharField(help_text='Point of contact for the TCCON site. Must be formatted "Name &lt;email&gt;". Separate multiple contacts with a semicolon, e.g. "Name1 &lt;email1&gt;; Name2 &lt;email2&gt;"', max_length=256),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='data_reference',
            field=models.TextField(blank=True, default='', help_text='Citation to use for the data from this TCCON site. Optional'),
        ),
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='site_reference',
            field=models.TextField(blank=True, default='', help_text='Citation to use for the TCCON site itself. Optional'),
        ),
    ]
