# Generated by Django 3.1.1 on 2022-09-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0006_auto_20210811_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfoupdate',
            name='short_location',
            field=models.CharField(default='', help_text='A short version of location, suitable for tables in papers', max_length=48),
            preserve_default=False,
        ),
    ]
