# Generated by Django 3.1.1 on 2022-09-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0007_siteinfoupdate_short_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfoupdate',
            name='short_location',
            field=models.CharField(help_text='A short version of location (32 characters), suitable for tables in papers', max_length=32),
        ),
    ]
