site_id_to_name = {
    "ae": "Ascension Island",
    "an": "Anmyeondo",
    "bi": "Bialystok",
    "br": "Bremen",
    "bu": "Burgos",
    "ci": "Caltech/Pasadena",
    "db": "Darwin",
    "df": "Dryden",
    "et": "East Trout Lake",
    "eu": "Eureka",
    "fc": "Four Corners",
    "gm": "Garmisch",
    "ht": "Arrival Heights",
    "hw": "Harwell",
    "if": "Indianapolis",
    "iz": "Izana",
    "jf": "JPL",
    "js": "Saga",
    "jx": "JPL",
    "ka": "Karlsruhe",
    "lh": "Lauder",
    "ll": "Lauder",
    "lr": "Lauder",
    "ma": "Manaus",
    "ni": "Nicosia",
    "ny": "Ny-Alesund",
    "oc": "Lamont",
    "or": "Orleans",
    "pa": "Park Falls",
    "pr": "Paris",
    "ra": "Reunion Island",
    "rj": "Rikubetsu",
    "so": "Sodankyla",
    "tk": "Tsukuba",
    "we": "Jena",
    "wg": "Wollongong",
    "xh": "Xianghe",
    "yk": "Yekaterinburg",
    "zs": "Zugspitze",
}


def get_sites_as_choices():
    return [t for t in site_id_to_name.items()]
