# Generated by Django 3.1.1 on 2020-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('siteid', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
