# Generated by Django 3.1.1 on 2020-09-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opstat', '0003_auto_20200908_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatushistory',
            name='sitename',
        ),
    ]
