# Generated by Django 3.1.1 on 2020-10-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opstat', '0004_remove_sitestatushistory_sitename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestatus',
            options={'permissions': [('ci_status', 'Can update the Caltech/Pasadena site status'), ('pa_status', 'Can update the Park Falls site status'), ('oc_status', 'Can update the Lamont site status'), ('wg_status', 'Can update the Wollongong site status')]},
        ),
    ]
