# Generated by Django 3.1.1 on 2022-04-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opstat', '0008_alter_sitestatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestatus',
            options={'permissions': [('ae_status', 'Can update the Ascension Island site status'), ('an_status', 'Can update the Anmyeondo site status'), ('bi_status', 'Can update the Bialystok site status'), ('br_status', 'Can update the Bremen site status'), ('bu_status', 'Can update the Burgos site status'), ('ci_status', 'Can update the Caltech/Pasadena site status'), ('db_status', 'Can update the Darwin site status'), ('df_status', 'Can update the Dryden site status'), ('et_status', 'Can update the East Trout Lake site status'), ('eu_status', 'Can update the Eureka site status'), ('fc_status', 'Can update the Four Corners site status'), ('gm_status', 'Can update the Garmisch site status'), ('hf_status', 'Can update the Hefei site status'), ('ht_status', 'Can update the Arrival Heights site status'), ('hw_status', 'Can update the Harwell site status'), ('if_status', 'Can update the Indianapolis site status'), ('iz_status', 'Can update the Izana site status'), ('jf_status', 'Can update the JPL site status'), ('js_status', 'Can update the Saga site status'), ('jx_status', 'Can update the JPL site status'), ('ka_status', 'Can update the Karlsruhe site status'), ('lh_status', 'Can update the Lauder site status'), ('ll_status', 'Can update the Lauder site status'), ('lr_status', 'Can update the Lauder site status'), ('ma_status', 'Can update the Manaus site status'), ('ni_status', 'Can update the Nicosia site status'), ('ny_status', 'Can update the Ny-Alesund site status'), ('oc_status', 'Can update the Lamont site status'), ('or_status', 'Can update the Orleans site status'), ('pa_status', 'Can update the Park Falls site status'), ('pr_status', 'Can update the Paris site status'), ('ra_status', 'Can update the Reunion Island site status'), ('rj_status', 'Can update the Rikubetsu site status'), ('so_status', 'Can update the Sodankyla site status'), ('tk_status', 'Can update the Tsukuba site status'), ('we_status', 'Can update the Jena site status'), ('wg_status', 'Can update the Wollongong site status'), ('xh_status', 'Can update the Xianghe site status'), ('yk_status', 'Can update the Yekaterinburg site status'), ('zs_status', 'Can update the Zugspitze site status')], 'verbose_name_plural': 'site statuses'},
        ),
    ]
