# Generated by Django 3.1.1 on 2022-01-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcreport',
            old_name='pres_err_comments',
            new_name='pres_err_cmts',
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='reviewer',
            field=models.CharField(max_length=128, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='Is timing error present'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_reproc',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('m', 'Maybe'), ('s', 'Site discretion')], max_length=1, verbose_name='Requires reprocessing'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when0e',
            field=models.DateField(blank=True, verbose_name='End of first timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when0s',
            field=models.DateField(blank=True, verbose_name='Start of first timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when1e',
            field=models.DateField(blank=True, verbose_name='End of second timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when1s',
            field=models.DateField(blank=True, verbose_name='Start of second timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when2e',
            field=models.DateField(blank=True, verbose_name='End of third timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when2s',
            field=models.DateField(blank=True, verbose_name='Start of third timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when3e',
            field=models.DateField(blank=True, verbose_name='End of fourth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when3s',
            field=models.DateField(blank=True, verbose_name='Start of fourth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when4e',
            field=models.DateField(blank=True, verbose_name='End of fifth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when4s',
            field=models.DateField(blank=True, verbose_name='Start of fifth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when5e',
            field=models.DateField(blank=True, verbose_name='End of sixth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when5s',
            field=models.DateField(blank=True, verbose_name='Start of sixth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when6e',
            field=models.DateField(blank=True, verbose_name='End of seventh timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when6s',
            field=models.DateField(blank=True, verbose_name='Start of seventh timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when7e',
            field=models.DateField(blank=True, verbose_name='End of eighth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when7s',
            field=models.DateField(blank=True, verbose_name='Start of eighth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when8e',
            field=models.DateField(blank=True, verbose_name='End of ninth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when8s',
            field=models.DateField(blank=True, verbose_name='Start of ninth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when9e',
            field=models.DateField(blank=True, verbose_name='End of tenth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when9s',
            field=models.DateField(blank=True, verbose_name='Start of tenth timing error'),
        ),
    ]
