# Generated by Django 3.1.1 on 2022-01-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0002_auto_20220125_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when0e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when0s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when1e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when1s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when2e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when2s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when3e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when3s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when4e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when4s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when5e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when5s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when6e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when6s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when7e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when7s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when8e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when8s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when9e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_when9s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when0e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when0s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when1e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when1s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when2e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when2s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when3e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when3s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when4e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when4s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when5e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when5s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when6e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when6s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when7e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when7s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when8e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when8s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when9e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_when9s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when0e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when0s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when1e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when1s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when2e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when2s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when3e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when3s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when4e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when4s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when5e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when5s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when6e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when6s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when7e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when7s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when8e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when8s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when9e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_when9s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when0e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when0s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when1e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when1s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when2e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when2s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when3e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when3s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when4e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when4s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when5e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when5s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when6e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when6s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when7e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when7s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when8e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when8s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when9e',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_when9s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when0e',
            field=models.DateField(blank=True, null=True, verbose_name='End of first timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when0s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of first timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when1e',
            field=models.DateField(blank=True, null=True, verbose_name='End of second timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when1s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of second timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when2e',
            field=models.DateField(blank=True, null=True, verbose_name='End of third timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when2s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of third timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when3e',
            field=models.DateField(blank=True, null=True, verbose_name='End of fourth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when3s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of fourth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when4e',
            field=models.DateField(blank=True, null=True, verbose_name='End of fifth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when4s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of fifth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when5e',
            field=models.DateField(blank=True, null=True, verbose_name='End of sixth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when5s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of sixth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when6e',
            field=models.DateField(blank=True, null=True, verbose_name='End of seventh timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when6s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of seventh timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when7e',
            field=models.DateField(blank=True, null=True, verbose_name='End of eighth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when7s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of eighth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when8e',
            field=models.DateField(blank=True, null=True, verbose_name='End of ninth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when8s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of ninth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when9e',
            field=models.DateField(blank=True, null=True, verbose_name='End of tenth timing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_when9s',
            field=models.DateField(blank=True, null=True, verbose_name='Start of tenth timing error'),
        ),
    ]
