# Generated by Django 3.1.1 on 2022-01-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0003_auto_20220126_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_follow_up',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1, verbose_name='Requires follow up'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_unstable',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], default='n', max_length=1, verbose_name='HCl VSF is unstable/jumps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when0',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='hcl_vsf_when9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_follow_up',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1, verbose_name='Requires follow up'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_unstable',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], default='n', max_length=1, verbose_name='O2 FS is off scale/jumps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when0',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='o2_fs_when9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='additional_cmts',
            field=models.TextField(blank=True, verbose_name='Additional comments'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='lse_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='lse_follow_up',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, verbose_name='Requires follow up'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='lse_present',
            field=models.CharField(choices=[('s', 'Small enough'), ('0', 'Uniformly 0'), ('l', 'Larger than usual')], max_length=1, verbose_name='LSE status'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nans_cmts',
            field=models.TextField(blank=True, verbose_name='Comments (include which windows are affected)'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nans_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, verbose_name='Mismatched numbers of NaNs'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nans_reproc',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('m', 'Maybe'), ('s', 'Site discretion')], max_length=1, verbose_name='Required reprocessing'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='netcdf_files',
            field=models.TextField(verbose_name='NetCDF files'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='nonlin_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='Nonlinearity present'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='Is pressure error present'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='pres_err_reproc',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('m', 'Maybe'), ('s', 'Site discretion')], max_length=1, verbose_name='Requires reprocessing'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='qc_flags_cmts',
            field=models.TextField(blank=True, verbose_name='Comments (include which flags are unusual)'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='qc_flags_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='Unusual flags present'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='qc_flags_reproc',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('m', 'Maybe'), ('s', 'Site discretion')], max_length=1, verbose_name='Required reprocessing'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_flag',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='Required release flagging'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='rolling_xluft_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='Out-of-family Xluft present'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='sg_present',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Uncertain')], max_length=1, verbose_name='SG stretch suggests pointing error'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='site',
            field=models.CharField(choices=[('ae', 'Ascension Island'), ('an', 'Anmyeondo'), ('bi', 'Bialystok'), ('br', 'Bremen'), ('bu', 'Burgos'), ('ci', 'Caltech/Pasadena'), ('db', 'Darwin'), ('df', 'Dryden'), ('et', 'East Trout Lake'), ('eu', 'Eureka'), ('fc', 'Four Corners'), ('gm', 'Garmisch'), ('ht', 'Arrival Heights'), ('hw', 'Harwell'), ('if', 'Indianapolis'), ('iz', 'Izana'), ('jf', 'JPL'), ('js', 'Saga'), ('jx', 'JPL'), ('ka', 'Karlsruhe'), ('lh', 'Lauder'), ('ll', 'Lauder'), ('lr', 'Lauder'), ('ma', 'Manaus'), ('ni', 'Nicosia'), ('ny', 'Ny-Alesund'), ('oc', 'Lamont'), ('or', 'Orleans'), ('pa', 'Park Falls'), ('pr', 'Paris'), ('ra', 'Reunion Island'), ('rj', 'Rikubetsu'), ('so', 'Sodankyla'), ('tk', 'Tsukuba'), ('we', 'Jena'), ('wg', 'Wollongong'), ('xh', 'Xianghe'), ('yk', 'Yekaterinburg'), ('zs', 'Zugspitze')], max_length=2, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='timing_cmts',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
    ]
