# Generated by Django 3.1.1 on 2022-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0004_auto_20220128_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
