# Generated by Django 3.1.1 on 2022-01-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0005_qcreport_modification_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcreport',
            old_name='o2_fs_comments',
            new_name='o2_fs_cmts',
        ),
    ]
