# Generated by Django 3.1.1 on 2022-02-17 06:00

import django.core.serializers.json
from django.db import migrations, models
import qcform.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0006_auto_20220128_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftQcReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=128, verbose_name='Reviewer')),
                ('draft_data', models.JSONField(decoder=qcform.models.DraftQcReport.DraftJSONDecoder, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='site',
            field=models.CharField(choices=[('ae', 'Ascension Island (ae)'), ('an', 'Anmyeondo (an)'), ('bi', 'Bialystok (bi)'), ('br', 'Bremen (br)'), ('bu', 'Burgos (bu)'), ('ci', 'Caltech/Pasadena (ci)'), ('db', 'Darwin (db)'), ('df', 'Dryden (df)'), ('et', 'East Trout Lake (et)'), ('eu', 'Eureka (eu)'), ('fc', 'Four Corners (fc)'), ('gm', 'Garmisch (gm)'), ('ht', 'Arrival Heights (ht)'), ('hw', 'Harwell (hw)'), ('if', 'Indianapolis (if)'), ('iz', 'Izana (iz)'), ('jc', 'JPL (jc)'), ('jf', 'JPL (jf)'), ('js', 'Saga (js)'), ('jx', 'JPL (jx)'), ('ka', 'Karlsruhe (ka)'), ('lh', 'Lauder (lh)'), ('ll', 'Lauder (ll)'), ('lr', 'Lauder (lr)'), ('ma', 'Manaus (ma)'), ('ni', 'Nicosia (ni)'), ('ny', 'Ny-Alesund (ny)'), ('oc', 'Lamont (oc)'), ('or', 'Orleans (or)'), ('pa', 'Park Falls (pa)'), ('pr', 'Paris (pr)'), ('ra', 'Reunion Island (ra)'), ('rj', 'Rikubetsu (rj)'), ('so', 'Sodankyla (so)'), ('tk', 'Tsukuba (tk)'), ('we', 'Jena (we)'), ('wg', 'Wollongong (wg)'), ('xh', 'Xianghe (xh)'), ('yk', 'Yekaterinburg (yk)'), ('zs', 'Zugspitze (zs)')], max_length=2, verbose_name='Site'),
        ),
    ]
