# Generated by Django 3.1.1 on 2022-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0007_auto_20220217_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftqcreport',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
