# Generated by Django 3.1.1 on 2022-02-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcform', '0008_draftqcreport_modification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftqcreport',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcform.qcreport'),
        ),
    ]
