# Generated by Django 3.1.1 on 2022-06-24 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcform', '0009_draftqcreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcreport',
            name='site',
            field=models.CharField(choices=[('ae', 'Ascension Island (ae)'), ('an', 'Anmyeondo (an)'), ('bi', 'Bialystok (bi)'), ('br', 'Bremen (br)'), ('bu', 'Burgos (bu)'), ('ci', 'Caltech/Pasadena (ci)'), ('db', 'Darwin (db)'), ('df', 'Dryden (df)'), ('et', 'East Trout Lake (et)'), ('eu', 'Eureka (eu)'), ('fc', 'Four Corners (fc)'), ('gm', 'Garmisch (gm)'), ('hf', 'Hefei (hf)'), ('ht', 'Arrival Heights (ht)'), ('hw', 'Harwell (hw)'), ('if', 'Indianapolis (if)'), ('iz', 'Izana (iz)'), ('jc', 'JPL (jc)'), ('jf', 'JPL (jf)'), ('js', 'Saga (js)'), ('jx', 'JPL (jx)'), ('ka', 'Karlsruhe (ka)'), ('lh', 'Lauder (lh)'), ('ll', 'Lauder (ll)'), ('lr', 'Lauder (lr)'), ('ma', 'Manaus (ma)'), ('ni', 'Nicosia (ni)'), ('ny', 'Ny-Alesund (ny)'), ('oc', 'Lamont (oc)'), ('or', 'Orleans (or)'), ('pa', 'Park Falls (pa)'), ('pr', 'Paris (pr)'), ('ra', 'Reunion Island (ra)'), ('rj', 'Rikubetsu (rj)'), ('so', 'Sodankyla (so)'), ('tk', 'Tsukuba (tk)'), ('we', 'Jena (we)'), ('wg', 'Wollongong (wg)'), ('xh', 'Xianghe (xh)'), ('yk', 'Yekaterinburg (yk)'), ('zs', 'Zugspitze (zs)')], max_length=2, verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='SiteReviewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('ae', 'Ascension Island (ae)'), ('an', 'Anmyeondo (an)'), ('bi', 'Bialystok (bi)'), ('br', 'Bremen (br)'), ('bu', 'Burgos (bu)'), ('ci', 'Caltech/Pasadena (ci)'), ('db', 'Darwin (db)'), ('df', 'Dryden (df)'), ('et', 'East Trout Lake (et)'), ('eu', 'Eureka (eu)'), ('fc', 'Four Corners (fc)'), ('gm', 'Garmisch (gm)'), ('hf', 'Hefei (hf)'), ('ht', 'Arrival Heights (ht)'), ('hw', 'Harwell (hw)'), ('if', 'Indianapolis (if)'), ('iz', 'Izana (iz)'), ('jc', 'JPL (jc)'), ('jf', 'JPL (jf)'), ('js', 'Saga (js)'), ('jx', 'JPL (jx)'), ('ka', 'Karlsruhe (ka)'), ('lh', 'Lauder (lh)'), ('ll', 'Lauder (ll)'), ('lr', 'Lauder (lr)'), ('ma', 'Manaus (ma)'), ('ni', 'Nicosia (ni)'), ('ny', 'Ny-Alesund (ny)'), ('oc', 'Lamont (oc)'), ('or', 'Orleans (or)'), ('pa', 'Park Falls (pa)'), ('pr', 'Paris (pr)'), ('ra', 'Reunion Island (ra)'), ('rj', 'Rikubetsu (rj)'), ('so', 'Sodankyla (so)'), ('tk', 'Tsukuba (tk)'), ('we', 'Jena (we)'), ('wg', 'Wollongong (wg)'), ('xh', 'Xianghe (xh)'), ('yk', 'Yekaterinburg (yk)'), ('zs', 'Zugspitze (zs)')], max_length=2, verbose_name='Site')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
