# Generated by Django 3.1.1 on 2022-06-24 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcform', '0010_auto_20220624_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereviewers',
            name='editor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'QC Reviewers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitereviewers',
            name='reviewer1',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'QC Reviewers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitereviewers',
            name='reviewer2',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'QC Reviewers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
